name: Create release

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build with Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: lts
      - run: yarn install --immutable --immutable-cache

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build

      - name: Disable husky hooks
        run: yarn prepublishOnly

      - name: Publish to npm
        run: |
          yarn config set npmAuthToken "$NPM_AUTH_TOKEN"
          yarn npm publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Create GitHub release
        run: |
          yarn pack --out gatsby-source-bgg.tgz
          tagname="${GITHUB_REF#refs/tags/}"
          gh release create "$tagname" gatsby-source-bgg.tgz --notes-file CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
